title:       "mfundo.cloud"
description: "Engineering insights from cloud infrastructure, system engineering, and software development"
author:      "Mfundo"
twitter_username: "mfundo"

# GitHub Pages compatible setup
plugins:      
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Markdown processing (syntax highlighting handled by Highlight.js)
markdown: kramdown
highlighter: none
kramdown:
  syntax_highlighter_opts:
    disable: true

# SASS configuration
sass:
  sass_dir: _sass
  style: compressed

# Simple pagination (GitHub Pages compatible)
paginate: 5
paginate_path: "/page:num/"

# Exclude documentation files from the site
exclude:
  - CHANGELOG.md
  - DEPLOYMENT.md
  - CONTENT_GUIDE.md
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/
  - scripts/
  - .gitignore
  - VERSION
  - assets/README.md

# Only include specific pages in header navigation
header_pages:
  - index.md
  - blog.md

url: "https://blog.mfundo.cloud"
baseurl: ""

# Giscus Comments Configuration
giscus:
  repo: "fractalops/fractalops.github.io"
  repo_id: "R_kgDOPNASqQ"
  category: "Announcements"
  category_id: "DIC_kwDOPNASqc4CtdfB"
  mapping: "pathname"
  strict: "0"
  reactions_enabled: "1"
  emit_metadata: "0"
  input_position: "bottom"
  theme: "dark"
  lang: "en"
  loading: "lazy" 