title:       "mfundo.cloud"
description: "Engineering insights from cloud infrastructure, system engineering, and software development"
author:      "Mfundo"

# GitHub Pages compatible setup
plugins:      
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Simple pagination (GitHub Pages compatible)
paginate: 5
paginate_path: "/page:num/"

# Exclude documentation files from the site
exclude:
  - CHANGELOG.md
  - DEPLOYMENT.md
  - CONTENT_GUIDE.md
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/
  - scripts/
  - .gitignore
  - VERSION
  - assets/README.md

# Only include specific pages in header navigation
header_pages:
  - index.md

# url will be set automatically by GitHub Pages
# Format: https://USERNAME.github.io/REPOSITORY_NAME 