title:       "mfundo.cloud"
description: "Engineering insights from cloud infrastructure, system engineering, and software development"
author:      "Mfundo"

# GitHub Pages compatible setup
plugins:      
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Syntax highlighting
highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false

# Simple pagination (GitHub Pages compatible)
paginate: 5
paginate_path: "/page:num/"

# Exclude documentation files from the site
exclude:
  - CHANGELOG.md
  - DEPLOYMENT.md
  - CONTENT_GUIDE.md
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/
  - scripts/
  - .gitignore
  - VERSION
  - assets/README.md

# Only include specific pages in header navigation
header_pages:
  - index.md
  - blog.md

url: "https://blog.mfundo.cloud"
baseurl: "" 